name: 'dns_pod_push'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  schedule:
    - cron: '*/30 * * * *' # 改为每 30 分钟全自动运行一次，确保优选 IP 永远处于最新状态
  workflow_dispatch: # 允许你随时在页面上手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        
      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          
      - name: 'Install dependencies'
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
      - name: '优化 @ 根域名'
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          SUB_DOMAIN: '@' # 强制指定根域名
          SECRETID: ${{ secrets.SECRETID }}
          SECRETKEY: ${{ secrets.SECRETKEY }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: python dnspod.py

      - name: '优化 www 子域名'
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          SUB_DOMAIN: 'www' # 强制指定 www 子域名
          SECRETID: ${{ secrets.SECRETID }}
          SECRETKEY: ${{ secrets.SECRETKEY }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: python dnspod.py
